var srcIndex = new Map(JSON.parse('[\
["ast_node",["",[],["ast_node_macro.rs","enum_deserialize.rs","lib.rs","spanned.rs"]]],\
["better_scoped_tls",["",[],["lib.rs"]]],\
["binding_macros",["",[],["lib.rs"]]],\
["dbg_swc",["",[["es",[["minifier",[["next",[],["check_size.rs","mod.rs"]]],["compare.rs","compare_opts.rs","ensure_size.rs","mod.rs","reduce.rs"]]],["exec_test.rs","mod.rs"]],["util",[],["minifier.rs","mod.rs"]]],["bundle.rs","main.rs"]]],\
["from_variant",["",[],["lib.rs"]]],\
["jsdoc",["",[],["ast.rs","input.rs","lib.rs"]]],\
["preset_env_base",["",[],["lib.rs","query.rs","version.rs"]]],\
["string_enum",["",[],["lib.rs"]]],\
["swc",["",[["config",[],["mod.rs"]]],["builder.rs","dropped_comments_preserver.rs","lib.rs","plugin.rs"]]],\
["swc_atoms",["",[],["lib.rs"]]],\
["swc_bundler",["",[["bundler",[["chunk",[["plan",[],["mod.rs"]]],["cjs.rs","computed_key.rs","merge.rs","mod.rs"]],["helpers",[],["mod.rs"]],["import",[],["mod.rs"]]],["export.rs","finalize.rs","keywords.rs","load.rs","mod.rs","optimize.rs","scope.rs"]],["debug",[],["mod.rs"]],["modules",[["sort",[],["chunk.rs","graph.rs","mod.rs","stmt.rs"]]],["mod.rs"]]],["dep_graph.rs","hash.rs","hook.rs","id.rs","inline.rs","lib.rs","load.rs","resolve.rs","util.rs"]]],\
["swc_cached",["",[],["lib.rs","regex.rs"]]],\
["swc_cli_impl",["",[["commands",[],["bundle.rs","compile.rs","lint.rs","minify.rs","mod.rs","plugin.rs"]],["util",[],["mod.rs","trace.rs"]]],["lib.rs"]]],\
["swc_common",["",[["errors",[],["diagnostic.rs","diagnostic_builder.rs","emitter.rs","lock.rs","mod.rs","snippet.rs","styled_buffer.rs"]],["plugin",[],["diagnostics.rs","metadata.rs","mod.rs","serialized.rs"]],["private",[],["mod.rs"]],["rustc_data_structures",[],["stable_hasher.rs"]],["syntax_pos",[],["analyze_source_file.rs","hygiene.rs"]],["util",[],["iter.rs","map.rs","mod.rs","move_map.rs","take.rs"]]],["collections.rs","comments.rs","eq.rs","input.rs","iter.rs","lib.rs","pass.rs","pos.rs","rustc_data_structures.rs","serializer.rs","source_map.rs","sync.rs","syntax_pos.rs"]]],\
["swc_compiler_base",["",[],["lib.rs"]]],\
["swc_config",["",[["config_types",[],["bool_config.rs","bool_or_data.rs","mod.rs","option.rs"]]],["lib.rs","merge.rs","module.rs","source_map.rs"]]],\
["swc_config_macro",["",[],["lib.rs","merge.rs"]]],\
["swc_core",["",[],["__diagnostics.rs","lib.rs","plugin.rs","quote.rs"]]],\
["swc_css",["",[],["lib.rs"]]],\
["swc_css_ast",["",[],["at_rule.rs","base.rs","lib.rs","selector.rs","token.rs","value.rs"]]],\
["swc_css_codegen",["",[["writer",[],["basic.rs","mod.rs"]]],["ctx.rs","emit.rs","lib.rs","list.rs","macros.rs"]]],\
["swc_css_codegen_macros",["",[],["lib.rs"]]],\
["swc_css_compat",["",[["compiler",[],["color_alpha_parameter.rs","color_hex_alpha.rs","color_hwb.rs","color_space_separated_parameters.rs","custom_media.rs","legacy_rgb_and_hsl.rs","media_query_ranges.rs","mod.rs","nesting.rs","selector_not.rs"]]],["feature.rs","lib.rs"]]],\
["swc_css_lints",["",[["rules",[],["at_rule_no_unknown.rs","block_no_empty.rs","color_hex_alpha.rs","color_hex_length.rs","color_no_invalid_hex.rs","custom_property_no_missing_var_function.rs","declaration_no_important.rs","font_family_no_duplicate_names.rs","keyframe_declaration_no_important.rs","mod.rs","no_duplicate_at_import_rules.rs","no_empty_source.rs","no_invalid_position_at_import_rule.rs","selector_max_class.rs","selector_max_combinators.rs","unit_no_unknown.rs"]]],["config.rs","dataset.rs","error.rs","lib.rs","pattern.rs","rule.rs"]]],\
["swc_css_minifier",["",[["compressor",[["math",[],["mod.rs"]]],["alpha_value.rs","angle.rs","calc_sum.rs","color.rs","container.rs","ctx.rs","declaration.rs","easing_function.rs","frequency.rs","import.rs","keyframes.rs","length.rs","media.rs","mod.rs","rules.rs","selector.rs","supports.rs","time.rs","transform_function.rs","unicode_range.rs","url.rs"]]],["lib.rs","options.rs","util.rs"]]],\
["swc_css_modules",["",[],["imports.rs","lib.rs"]]],\
["swc_css_parser",["",[["lexer",[],["mod.rs"]],["parser",[["at_rules",[],["mod.rs"]],["selectors",[],["mod.rs"]],["syntax",[],["mod.rs"]],["values_and_units",[],["mod.rs"]]],["input.rs","macros.rs","mod.rs","util.rs"]]],["error.rs","lib.rs","macros.rs"]]],\
["swc_css_prefixer",["",[],["lib.rs","options.rs","prefixer.rs"]]],\
["swc_css_utils",["",[],["lib.rs"]]],\
["swc_css_visit",["",[],["lib.rs"]]],\
["swc_ecma_ast",["",[],["class.rs","decl.rs","expr.rs","function.rs","ident.rs","jsx.rs","lib.rs","list.rs","lit.rs","macros.rs","module.rs","module_decl.rs","operators.rs","pat.rs","prop.rs","source_map.rs","stmt.rs","typescript.rs"]]],\
["swc_ecma_codegen",["",[["text_writer",[],["basic_impl.rs","semicolon.rs"]]],["comments.rs","config.rs","decl.rs","expr.rs","jsx.rs","lib.rs","macros.rs","stmt.rs","text_writer.rs","typescript.rs","util.rs"]]],\
["swc_ecma_codegen_macros",["",[],["fold.rs","lib.rs"]]],\
["swc_ecma_compat_bugfixes",["",[],["async_arrows_in_class.rs","edge_default_param.rs","lib.rs","safari_id_destructuring_collision_in_function_expression.rs","template_literal_caching.rs"]]],\
["swc_ecma_compat_common",["",[],["lib.rs","macros.rs","regexp.rs"]]],\
["swc_ecma_compat_es2015",["",[["block_scoping",[],["mod.rs","vars.rs"]],["classes",[],["constructor.rs","mod.rs","prop_name.rs"]],["regenerator",[],["mod.rs"]]],["arrow.rs","block_scoped_fn.rs","computed_props.rs","destructuring.rs","duplicate_keys.rs","for_of.rs","function_name.rs","generator.rs","instanceof.rs","lib.rs","new_target.rs","object_super.rs","parameters.rs","shorthand_property.rs","spread.rs","sticky_regex.rs","template_literal.rs","typeof_symbol.rs"]]],\
["swc_ecma_compat_es2016",["",[],["exponentiation.rs","lib.rs"]]],\
["swc_ecma_compat_es2017",["",[],["async_to_generator.rs","lib.rs"]]],\
["swc_ecma_compat_es2018",["",[],["lib.rs","object_rest.rs","object_rest_spread.rs","object_spread.rs"]]],\
["swc_ecma_compat_es2019",["",[],["lib.rs","optional_catch_binding.rs"]]],\
["swc_ecma_compat_es2020",["",[],["export_namespace_from.rs","lib.rs","nullish_coalescing.rs","optional_chaining.rs"]]],\
["swc_ecma_compat_es2021",["",[],["lib.rs","logical_assignments.rs"]]],\
["swc_ecma_compat_es2022",["",[["class_properties",[],["class_name_tdz.rs","member_init.rs","mod.rs","private_field.rs","this_in_static.rs","used_name.rs"]]],["lib.rs","optional_chaining_impl.rs","private_in_object.rs","static_blocks.rs"]]],\
["swc_ecma_compat_es3",["",[],["lib.rs","member_expr_lits.rs","prop_lits.rs","reserved_word.rs"]]],\
["swc_ecma_ext_transforms",["",[],["jest.rs","lib.rs"]]],\
["swc_ecma_lints",["",[["rules",[],["const_assign.rs","duplicate_bindings.rs","duplicate_exports.rs","mod.rs","no_dupe_args.rs","utils.rs"]]],["config.rs","lib.rs","rule.rs"]]],\
["swc_ecma_loader",["",[["resolvers",[],["lru.rs","mod.rs","node.rs","tsc.rs"]]],["lib.rs","resolve.rs"]]],\
["swc_ecma_minifier",["",[["compress",[["optimize",[],["arguments.rs","bools.rs","collapse_vars.rs","conditionals.rs","dead_code.rs","evaluate.rs","if_return.rs","iife.rs","inline.rs","loops.rs","mod.rs","ops.rs","props.rs","sequences.rs","strings.rs","switches.rs","unused.rs","util.rs"]],["pure",[],["arrows.rs","bools.rs","conds.rs","ctx.rs","dead_code.rs","drop_console.rs","evaluate.rs","if_return.rs","loops.rs","misc.rs","mod.rs","numbers.rs","properties.rs","sequences.rs","strings.rs","unsafes.rs","vars.rs"]],["util",[],["mod.rs"]]],["hoist_decls.rs","mod.rs"]],["metadata",[],["mod.rs"]],["option",[],["mod.rs","terser.rs"]],["pass",[["mangle_names",[],["mod.rs","preserver.rs","private_name.rs"]]],["expand_names.rs","global_defs.rs","mangle_props.rs","merge_exports.rs","mod.rs","postcompress.rs","precompress.rs"]],["util",[],["base54.rs","mod.rs","size.rs","sort.rs","unit.rs"]]],["debug.rs","eval.rs","js.rs","lib.rs","macros.rs","mode.rs","program_data.rs","timing.rs"]]],\
["swc_ecma_parser",["",[["lexer",[],["comments_buffer.rs","input.rs","jsx.rs","mod.rs","number.rs","state.rs","table.rs","util.rs","whitespace.rs"]],["parser",[["expr",[],["ops.rs","verifier.rs"]],["stmt",[],["module_item.rs"]]],["class_and_fn.rs","expr.rs","ident.rs","input.rs","jsx.rs","macros.rs","mod.rs","object.rs","pat.rs","stmt.rs","typescript.rs","util.rs"]]],["error.rs","lib.rs","macros.rs","token.rs"]]],\
["swc_ecma_preset_env",["",[["corejs2",[],["builtin.rs","data.rs","entry.rs","mod.rs"]],["corejs3",[],["builtin.rs","compat.rs","data.rs","entry.rs","mod.rs","usage.rs"]],["regenerator",[],["mod.rs"]]],["lib.rs","transform_data.rs","util.rs"]]],\
["swc_ecma_quote",["",[],["clone.rs","lib.rs"]]],\
["swc_ecma_quote_macros",["",[["ast",[],["class.rs","decl.rs","enums.rs","expr.rs","id.rs","lit.rs","mod.rs","module_decl.rs","pat.rs","prop.rs","stmt.rs","typescript.rs"]]],["builder.rs","ctxt.rs","input.rs","lib.rs","ret_type.rs"]]],\
["swc_ecma_testing",["",[],["lib.rs"]]],\
["swc_ecma_transforms",["",[],["lib.rs"]]],\
["swc_ecma_transforms_base",["",[["helpers",[],["mod.rs"]],["hygiene",[],["mod.rs"]],["rename",[["analyzer",[],["mod.rs","reverse_map.rs","scope.rs"]]],["collector.rs","eval.rs","mod.rs","ops.rs"]],["resolver",[],["mod.rs"]]],["assumptions.rs","ext.rs","feature.rs","fixer.rs","lib.rs","native.rs","pass.rs","perf.rs","quote.rs","scope.rs"]]],\
["swc_ecma_transforms_classes",["",[],["lib.rs","macros.rs","super_field.rs"]]],\
["swc_ecma_transforms_compat",["",[],["class_fields_use_set.rs","lib.rs","reserved_words.rs"]]],\
["swc_ecma_transforms_macros",["",[],["common.rs","fast.rs","lib.rs","parallel.rs"]]],\
["swc_ecma_transforms_module",["",[["umd",[],["config.rs"]]],["amd.rs","common_js.rs","import_analysis.rs","lib.rs","module_decl_strip.rs","module_ref_rewriter.rs","path.rs","rewriter.rs","system_js.rs","top_level_this.rs","umd.rs","util.rs"]]],\
["swc_ecma_transforms_optimization",["",[["simplify",[["branch",[],["mod.rs"]],["dce",[],["mod.rs"]],["expr",[],["mod.rs"]],["inlining",[],["mod.rs","scope.rs"]]],["const_propagation.rs","mod.rs"]]],["const_modules.rs","debug.rs","inline_globals.rs","json_parse.rs","lib.rs"]]],\
["swc_ecma_transforms_proposal",["",[["decorators",[["legacy",[],["metadata.rs","mod.rs"]]],["mod.rs"]]],["decorator_2022_03.rs","explicit_resource_management.rs","export_default_from.rs","import_assertions.rs","lib.rs"]]],\
["swc_ecma_transforms_react",["",[["display_name",[],["mod.rs"]],["jsx",[],["mod.rs","static_check.rs"]],["jsx_self",[],["mod.rs"]],["jsx_src",[],["mod.rs"]],["pure_annotations",[],["mod.rs"]],["refresh",[],["hook.rs","mod.rs","options.rs","util.rs"]]],["lib.rs"]]],\
["swc_ecma_transforms_testing",["",[],["babel_like.rs","lib.rs"]]],\
["swc_ecma_transforms_typescript",["",[],["config.rs","lib.rs","macros.rs","strip_import_export.rs","strip_type.rs","transform.rs","ts_enum.rs","typescript.rs","utils.rs"]]],\
["swc_ecma_usage_analyzer",["",[["alias",[],["ctx.rs","mod.rs"]],["analyzer",[],["ctx.rs","mod.rs","storage.rs"]]],["lib.rs","marks.rs","util.rs"]]],\
["swc_ecma_utils",["",[["function",[],["fn_env_hoister.rs","function_wrapper.rs","mod.rs"]]],["constructor.rs","factory.rs","ident.rs","lib.rs","macros.rs","node_ignore_span.rs","number.rs","parallel.rs","stack_size.rs","value.rs","var.rs"]]],\
["swc_ecma_visit",["",[],["lib.rs"]]],\
["swc_ecmascript",["",[],["lib.rs"]]],\
["swc_eq_ignore_macros",["",[],["lib.rs"]]],\
["swc_error_reporters",["",[],["handler.rs","lib.rs"]]],\
["swc_estree_ast",["",[],["class.rs","comment.rs","common.rs","decl.rs","expr.rs","flavor.rs","flow.rs","jsx.rs","lib.rs","lit.rs","module.rs","object.rs","pat.rs","ser.rs","stmt.rs","typescript.rs"]]],\
["swc_estree_compat",["",[["babelify",[],["class.rs","decl.rs","expr.rs","function.rs","ident.rs","jsx.rs","lit.rs","mod.rs","module.rs","module_decl.rs","operators.rs","pat.rs","prop.rs","stmt.rs","typescript.rs"]],["swcify",[],["class.rs","ctx.rs","expr.rs","jsx.rs","lit.rs","mod.rs","pat.rs","program.rs","stmt.rs","typescript.rs"]]],["lib.rs"]]],\
["swc_fast_graph",["",[],["digraph.rs","lib.rs"]]],\
["swc_graph_analyzer",["",[],["lib.rs"]]],\
["swc_html",["",[],["lib.rs"]]],\
["swc_html_ast",["",[],["base.rs","lib.rs","token.rs"]]],\
["swc_html_codegen",["",[["writer",[],["basic.rs","mod.rs"]]],["ctx.rs","emit.rs","lib.rs","list.rs","macros.rs"]]],\
["swc_html_codegen_macros",["",[],["lib.rs"]]],\
["swc_html_minifier",["",[],["lib.rs","option.rs"]]],\
["swc_html_parser",["",[["lexer",[],["mod.rs"]],["parser",[],["active_formatting_element_stack.rs","doctypes.rs","input.rs","macros.rs","mod.rs","node.rs","open_elements_stack.rs"]]],["error.rs","lib.rs","macros.rs"]]],\
["swc_html_utils",["",[],["lib.rs"]]],\
["swc_html_visit",["",[],["lib.rs"]]],\
["swc_macros_common",["",[["derive",[],["generics.rs"]]],["binder.rs","derive.rs","lib.rs","prelude.rs","syn_ext.rs"]]],\
["swc_malloc",["",[],["lib.rs"]]],\
["swc_node_bundler",["",[["loaders",[],["json.rs","mod.rs","swc.rs"]],["v1",[["module",[],["mod.rs"]]],["mod.rs","optimization.rs","output.rs","resolve.rs"]]],["lib.rs"]]],\
["swc_node_comments",["",[],["lib.rs"]]],\
["swc_nodejs_common",["",[],["lib.rs"]]],\
["swc_plugin",["",[],["lib.rs","pseudo_scoped_key.rs"]]],\
["swc_plugin_macro",["",[],["lib.rs"]]],\
["swc_plugin_proxy",["",[["comments",[],["host_comments_storage.rs","mod.rs","plugin_comments_proxy.rs"]],["memory_interop",[],["mod.rs","read_returned_result_from_host.rs"]],["metadata",[],["mod.rs","transform_plugin_metadata.rs"]],["source_map",[],["mod.rs","plugin_source_map_proxy.rs"]]],["lib.rs"]]],\
["swc_plugin_runner",["",[],["cache.rs","host_environment.rs","lib.rs","plugin_module_bytes.rs","transform_executor.rs","wasix_runtime.rs"]]],\
["swc_plugin_testing",["",[],["lib.rs"]]],\
["swc_timer",["",[],["lib.rs"]]],\
["swc_trace_macro",["",[],["lib.rs"]]],\
["swc_transform_common",["",[],["lib.rs","output.rs"]]],\
["swc_typescript",["",[["fast_dts",[],["mod.rs"]]],["diagnostic.rs","lib.rs"]]],\
["swc_visit",["",[["util",[],["map.rs","mod.rs","move_map.rs"]]],["lib.rs"]]],\
["swc_visit_macros",["",[],["lib.rs"]]],\
["swc_x_optimizer",["",[],["lib.rs"]]],\
["swc_xml",["",[],["lib.rs"]]],\
["swc_xml_ast",["",[],["base.rs","lib.rs","token.rs"]]],\
["swc_xml_codegen",["",[["writer",[],["basic.rs","mod.rs"]]],["ctx.rs","emit.rs","lib.rs","list.rs","macros.rs"]]],\
["swc_xml_codegen_macros",["",[],["lib.rs"]]],\
["swc_xml_parser",["",[["lexer",[],["mod.rs"]],["parser",[],["input.rs","macros.rs","mod.rs","node.rs","open_elements_stack.rs"]]],["error.rs","lib.rs"]]],\
["swc_xml_visit",["",[],["lib.rs"]]],\
["testing",["",[["errors",[],["mod.rs","stderr.rs"]]],["diag_errors.rs","json.rs","lib.rs","macros.rs","output.rs","paths.rs","string_errors.rs"]]],\
["testing_macros",["",[],["fixture.rs","lib.rs"]]],\
["xtask",["",[["es",[],["minifier.rs","mod.rs"]],["git",[["reduce",[],["core_ver.rs","mod.rs"]]],["mod.rs"]],["npm",[],["mod.rs","nightly.rs","util.rs"]],["util",[],["mod.rs"]]],["bench.rs","clean.rs","main.rs"]]]\
]'));
createSrcSidebar();
